# Generated by Django 4.2.1 on 2023-05-28 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_region_organizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('organizacion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.organizacion')),
            ],
        ),
    ]
