# Generated by Django 4.2.1 on 2023-05-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sexo_transito'),
    ]

    operations = [
        migrations.AddField(
            model_name='transito',
            name='sexo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sexo'),
        ),
    ]
