# Generated by Django 4.2.1 on 2023-05-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_transito_sexo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transito',
            name='animal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.animales'),
        ),
    ]
